name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:
    inputs:
      app_id:
        description: 'com.example.sandbox'
        required: true
      branch:
        description: 'master'
        required: true
        default: 'master'

jobs:
  build:
    name: Setup Environment and build
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: set up JDK 11
        uses: actions/setup-java@v3.4.1
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Check KtLint
        run: ./gradlew ktlintCheck --stacktrace

      - name: Check Android lint
        run: ./gradlew lintDebug --stacktrace

      - name: Run Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Unit Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: |
              app/build/reports
              uiBox/build/reports

      - name: Build with Gradle
        run: ./gradlew clean assembleRelease --stacktrace

      - name: Upload the signed artifact
        uses: actions/upload-artifact@v3
        with:
          name: signed-app
          path: app/build/outputs/apk/release/app-release.apk


  androidTest:
    needs: [ build ]
    name: Instrumental Tests
    runs-on: macOS-latest
    timeout-minutes: 45

    steps:
    - name: Checkout the code to specific branch
      uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3.4.1
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Android tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 31
        arch: x86_64
        disable-animations: false
        disk-size: 2000M
        heap-size: 600M
        script: ./gradlew connectedDebugAndroidTest --stacktrace

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: android-test-reports
        path: app/build/reports/androidTests
